export const appConfig = {
  mainDomain: 'https://api.mystylist.in/',
};

export const endPoints = {
  expertLogin: `user/expert-login`,
  expertRegister: `user/expert-register`,
  allDisName: `user/getAllDistrictName`,
  verifyOtp: `user/verify-otp`,
  createExpertOffer: `generateOffer/generateOffer`,
  createPackage: 'generatePackage/generatePackage',
  allCategories: `category/getAllCategories`,
  generateCoupon: `generateCoupon/generateCoupon`,
  getAllOffersByUser: `generateOffer/getAllOffersByUser`,
  getAllCouponsByUser: `generateCoupon/getAllCouponsByUser`,
  generatePackage: `generatePackage/generatePackage`,
  getAllPackageByUser: `generatePackage/getAllPackageByUser`,
  getAllDatesOFUser: `expertUnavailability/getExpertAvailabilityForDate`,
  markAsBusy: `expertUnavailability/addExpertUnavailability`,
  getUserDetails: `user/getUserDetails`,
  getAllExpertsImages: `user/getAllExpertsImages`,
  markAsUnBusy: `expertUnavailability/removeUserUnavailability`,
  getCampaigns: `campaign/getCampaignsByCriteria`,
  getCampaignDetails: `campaign/getCampaignForMobile`,
  getAllFAQForMobile: `faq/getAllFAQForMobile`,
  getAllExpertReview: `review/getAllExpertReview`,
  getAllPolicy: `cms/getCMSPageForMobile/64fc1db93f161dd8548acb18`,
  getAllTerms: `cms/getCMSPageForMobile/64fc1e863f161dd8548acb1e`,
  getAboutUs: `cms/getCMSPageForMobile/64fc1d003f161dd8548acb12`,
  getAppointments: `appointment/getAppointmentForMobile`,
  getAppointmentDetails: `appointment/getAppointmentDetails`,
  getAllFollowersOfExpert: `followers/getAllFollowersOfExpert`,
  getUpcomingJobs: `salonJob/getAllJobsForUsers`,
  getSavedJobs: `bookmarkJob/getAllBookmarkedJobs`,
  bookmarkJob: `bookmarkJob/bookmarkJob`,
  unBookmarkJob: `bookmarkJob/unbookmarkJob`,
  getOfferDetails: `generateOffer/getOfferDetails`,
  getPackageDetails: `generatePackage/getPackageDetails`,
  getUsersList: `user/getUsersList`,
  createRoom: `user/createRoom`,
  getExpertServices: `/service/getAllServicesForMobile`,
  getExpertSeubServices: `/service/getAllSubServicesForMobile`,
  jobApply: `JobApplication/applyJobApplication`,
  getJobDetails: 'salonJob/getJobsDetails',
  getProductListItems: `/product/getAlllProductName`,
};
