const images = {
  AppLogo: require('./appLogo.png'),
  Camera: require('./camera.png'),
  MyStylistLogo: require('./mystylistLogo.png'),
  BackwardIcon: require('./backwardIcon.png'),
  ProfileIcon: require('./profile_icon.png'),
  NotificationIcon: require('./notification.png'),
  NotificationFill: require('./notificationFill.png'),
  DrawerIcon: require('./drawer.png'),
  PhoneIcon: require('./phone.png'),
  SaloonIcon: require('./saloon.png'),
  SearchIcon: require('./ssearchIcon.png'),
  Search: require('./search.png'),
  HomeIcon: require('./homes.png'),
  AppointmentsIcon: require('./appointments.png'),
  DownArrow: require('./downArrow.png'),
  RightArrow: require('./rightArrow.png'),
  SelectedProfileIcon: require('./selectedProfileIcon.png'),
  BellIcon: require('./bell.png'),
  userDefaultIcon: require('./userDefault.png'),
  GalaryIcon: require('./Gallery.png'),
  StarIcon: require('./star.png'),
  DownArrowLong: require('./arrowDown.png'),
  YellowStart: require('./star.png'),
  FaqIcon: require('./faqIcon.png'),
  EmptyStarIcon: require('./emptyStarNew.png'),
  CalendarIcon: require('./calender.png'),
  PercentageIcon: require('./offer.png'),
  GrowthIcon: require('./growth.png'),
  DashbroadIcon: require('./Gallery.png'),
  DiyIcon: require('./markBusy.png'),
  TagIcon: require('./tag.png'),
  BoxIconPackage: require('./packages.png'),
  ShareIcon: require('./share.png'),
  EmailIcon: require('./email.png'),
  ChatPrimary: require('./chatPrimary.png'),
  SeenIcon: require('./seen.png'),
  BusyIcon: require('./busy.png'),
  NameIcon: require('./selectedProfileIcon.png'),
  TransactionIcon: require('./transaction.png'),
  whatsappIcon: require('./whatsapp.png'),
  ArrowDown: require('./downArrow.png'),
  HalfStar: require('./halfStar.png'),
  playIcon: require('./playIcon.png'),
  EmptyStar: require('./emptyStar.png'),
  FollowersIcon: require('./followers.png'),
  FollowerIcon: require('./followerIcon.png'),
  logoutIcon: require('./logout.png'),
  PrivacyIcon: require('./privacy.png'),
  ReferIcon: require('./refer.png'),
  PlusIcon: require('./plus.png'),
  MinusIcon: require('./minus.png'),
  Check: require('./check.png'),
  RectangleLoginIcon: require('./RectangleLogin.jpg'),
  CrossIcon: require('./cross.png'),
  FeedIcon: require('./feed.png'),
  ChatIcon: require('./chat.png'),
  SendIcon: require('./send.png'),
  SmileIcon: require('./smile.png'),
  MikeIcon: require('./mike.png'),
  DistanceIcon: require('./distance.png'),
  AttachmentIcon: require('./attachment.png'),
  profile: require('./profile.png'),
  CampaignsIcon: require('./campaigns.png'),
  AppointmentIcon: require('./appointmentIcon.png'),
  AvailabilityIcon: require('./availability.png'),
  JobIcon: require('./job.png'),
  LocationIcon: require('./location.png'),
  ThreeDotsIcon: require('./threeDots.png'),
  ThreeDotsHorizontal: require('./more.png'),
  SortIcon: require('./sort.png'),
  HeartIcon: require('./heart.png'),
  forwardMessageIcon: require('./forwardMessage.png'),
  plussIcon: require('./plus.png'),
  MessageIcon: require('./messageQuestion.png'),
  RightForward: require('./rightForward.png'),
  Location: require('./location.png'),
  WalletIcon: require('./wallet.png'),
  PinIcon: require('./pin.png'),
  BackIcon: require('./back.png'),
  NextIcon: require('./next.png'),
  UpArrow: require('./upArrow.png'),
  TriangleIcon: require('./triangle.png'),
  ParkingSpace: require('./car.png'),
  Music: require('./music.png'),
  Wifi: require('./wifi.png'),
  WatchIcon: require('./watch.png'),
  SelfieCamera: require('./selfieCamera.png'),
  ChildFriendly: require('./childFriendly.png'),
  CreditCard: require('./creditCard.png'),
  PetsFriendly: require('./petsFriendly.png'),
  PowerBackup: require('./powerBackup.png'),
  YoutubeIcon: require('./tube.png'),
  SendDark: require('./sendDark.png'),
  ImageIcon: require('./imageIcon.png'),
  VideoCamera: require('./videoCamera.png'),
  EditIcon: require('./edit.png'),
  Bookmark: require('./bookmark.png'),
  BookmarkFilled: require('./bookmarkFilled.png'),
  
  
  loginbg:require('./loginbg.png'),
  gradient_model:require('./gradient_model.png'),
  gradient_input:require('./gradient_input.png'),
  DownArrows:require('./chevDown.png'),
  gradient_bg:require('./gradient_bg.png'),
  Back:require('./backArrow.png'),
  Address:require('./addressess.png'),
  HomeBell:require('./homebell.png'),
  avatar:require('./avatar.png'),
  dropDown:require('./dropDown.png'),
  homelocation:require('./homelocation.png'),
  expert1:require('./expert1.png'),
  expert2:require('./expert2.png'),
  expert3:require('./expert3.png'),
  expert4:require('./expert4.png'),
  expert5:require('./expert5.png'),
  expert6:require('./expert6.png'),
  expert7:require('./expert7.png'),
  expert8:require('./expert8.png'),
  expert9:require('./expert9.png'),
  locationpin:require('./locationpin.png'),
  close:require('./close.png'),
  success:require('./success.png'),
  offerbanner:require('./offerbanner.png'),
  locationAllow:require('./locationallow.png'),
  bottomhome:require('./bottomhome.png'),
  bottomappointment:require('./bottomappointment.png'),
  bottomchat:require('./bottomchat.png'),
  bottomprofile:require('./bottomprofile.png'),
  headerSearch:require('./headerSearch.png'),
  add:require('./add.png'),
  datepicker:require('./datepicker.png'),
  upload:require('./upload.png'),
  packagebanner:require('./packagebanner.png'),
  badgebg:require('./badgebg.png'),
  cardbg:require('./cardbg.png'),
  wom1:require('./wom1.png'),
  wom2:require('./wom2.png'),
  chaticon:require('./chaticon.png'),
  callicon:require('./callicon.png'),
  lefticon:require('./leftArrow.png'),
  righticon:require('./righticon.png'),
  clockicon:require('./clockicon.png'),
  collapseArrow:require('./collapseArrow.png'),
  services:require('./services.png'),
  buttonbg:require('./buttonbg.png'),
  uploadicon:require('./uploadicon.png'),
  floatarrow:require('./floatarrow.png'),
  dashbroadbutton:require('./dashbroadbutton.png'),
  cameraicon:require('./cameraicon.png'),
  trash:require('./trash.png'),
  UpArrows:require('./chevUp.png'),
  profileimg:require('./profileimg.png'),
  locationicon:require('./locationicon.png'),
  walleticon:require('./walleticon.png'),
  notificationicon:require('./notificationicon.png'),
  outlinestaricon:require('./outlinestaricon.png'),
  faqicon:require('./faq.png'),
  termsicon:require('./termsicon.png'),
  privacyicon:require('./privacyicon.png'),
  reviewicon:require('./outlinestaricon.png'),
  trashicon:require('./trashicon.png'),
  contactus:require('./contactus.png'),
  verifybadge:require('./verifybadge.png'),
  facebook:require('./facebook.png'),
  instagram:require('./instagram.png'),
  locationmarker:require('./locationmarker.png'),
  cardbg2:require('./cardbg2.png'),
  cardbg3:require('./cardbg3.png'),
  userIcon:require('./user.png'),
  sendicon:require('./sendicon.png')
};

export default images;
